name: Lint

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort
    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exit-zero
        # Exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --statistics
    - name: Check formatting with black
      run: |
        # For now, just report what would be reformatted but don't fail
        black --check --diff . || true
    - name: Check imports with isort
      run: |
        # For now, just report what would be reformatted but don't fail
        isort --check-only --diff --profile black . || true
